[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
proof_of_reserves = "6HP4rFEb9v9yiSkgRTHXvYCsEAx6pxqaF7R4dyK2s7BV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
#wallet = "~/Documents/proof-of-reserves/.secrets/tokenAuthority.json"
wallet = "~/projects/ud/proof-of-reserves/.secrets/tokenAuthority.json"

[scripts]
test = "cargo test"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "Gt9S41PtjR58CbG9JhJ3J6vxesqrNAswbWYbLNTMZA3c"
program = "deps/verifier.so"
upgradeable = true

[[test.genesis]]
address = "EjVftbXwfRZoZDzJ6eHArCqiBiPHBLq5zajRqMiHGH1A"
program = "deps/access_controller.so"
upgradeable = true

[test.validator]
bind_address = "0.0.0.0"
ledger = ".anchor/test-ledger"
rpc_port = 8899
