[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
oracle_updater = "DKuMPrGWQqGfCu9TbT6hLB6JCoLSryCaHLhLdYieY1KT"
wrap_uranium = "3JmfgAqnGnyh8pXGo8w8bi6MGjfd3Jn4aaKqfJgb7UcQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/hongjan/Documents/token-deployer/.secrets/tokenAuthority.json"

[scripts]
test = "cargo test"

[test.validator]
[[test.genesis]]
address = "Gt9S41PtjR58CbG9JhJ3J6vxesqrNAswbWYbLNTMZA3c"
program = "deps/verifier.so"
upgradeable = true

[[test.genesis]]
address = "EjVftbXwfRZoZDzJ6eHArCqiBiPHBLq5zajRqMiHGH1A"
program = "deps/access_controller.so"
upgradeable = true
