[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
oracle_updater = "8y6CXiQsLVXa98ASAeC9oMmo9GV7n7Z2mCwUJysYjUYs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../.secrets/tokenAuthority.json"

[scripts]
test = "cargo test"
