[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
oracle_updater = "Hjd7xmM1oU47c9bP2qPG28G8LFTAcoi3qX5K8TvxshEE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
